name: My Test Workflow

on: [push]

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "hello github actions!"

    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
          - name: Check out this repo
            uses: actions/checkout@v3

          - name: Install dependencies
            run: sudo apt install -y build-essential python3

          - run: pwd

          - name: Run Test
            run: pyhton3 test.py 
